coverage:
  status:
    project:
      default:
        # basic
        target: 70%
        threshold: 30%
        base: auto
    patch:
      default:
        # basic
        target: 70%
        threshold: 30%
        base: auto 
